# Generated by Django 6.0.1 on 2026-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
