# Generated by Django 6.0.1 on 2026-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='noir', max_length=7),
        ),
    ]
